production: false

profiler:
  address: telegraf.monitoring.svc:8125
  service: ems

graceful:
  port: 9090
  waittime: 10s

#DB config
ts_mongodb:
  host: localhost:27017
  user:
  pass:
  authdb: admin
  replica: ""
  db: telegram-bot

#Service config
ts_service:
  mode: 0
  destination: order
  env: staging
  user: ems
  pass: emsinternal
  error_url: https://staging-truck-gw.ghn.dev
  hub_url: https://staging-truck-gw.ghn.dev
  authen_url: https://staging-truck-gw.ghn.dev/ums/v1/internal
  logger_url: https://staging-truck-gw.ghn.dev/ems/v1/tlogger/internal/messages
  logger_routingkey: ts.tlogger


#Authen config
ts_encryption:
  jwt_secret: secret
  basic:
    #Internal
    - username: ums
      password: umsinternal
    - username: cdms
      password: cdmsinternal
    - username: tars
      password: tarsinternal
    - username: tms
      password: tmsinternal
    - username: srms
      password: srmsinternal
    - username: ems
      password: emsinternal
    - username: tsms
      password: tsmsinternal
    - username: ptms
      password: ptmsinternal
    - username: tlogger
      password: tloggerinternal


